### ISSUE TITLE
Cassandra 4.0 won't nest it's traces

### ISSUE THREAD

**Issue by piotrmaslanka** [infracloudio/cassandra-jaeger-tracing#10]
Blocked on [this](https://stackoverflow.com/questions/74146678/ferrying-opentelemetry-span-context-via-org-apache-cassandra-net-message-header).

**Comment by piotrmaslanka** [comment]
Ok I've escalated the issue .to [CASSANDRA-17981](https://issues.apache.org/jira/browse/CASSANDRA-17981)

**Comment by piotrmaslanka** [comment]
Good news, @bhavin192 , they [promised us](https://issues.apache.org/jira/browse/CASSANDRA-17981) an actual patch for that!

**Comment by bhavin192** [comment]
That's awesome! 
PS: I will take a look at your PR/issues in a few days as I get some time.

**Comment by piotrmaslanka** [comment]
https://github.com/apache/cassandra/commit/f01d2b4a3ca114ac58d95befcab3dbbad9d960aa to be added as soon as I upgrade my cluster to Cassandra 4.1
