### ISSUE TITLE
Jaeger is recommending that we switch to OpenTelemetry

### ISSUE THREAD

**Issue by piotrmaslanka** [infracloudio/cassandra-jaeger-tracing#11]
https://www.jaegertracing.io/docs/1.18/opentelemetry/

**Comment by bhavin192** [comment]
Yes we should switch to OTel eventually, the Jaeger client we are using are not maintained now.

**Comment by piotrmaslanka** [comment]
This is harder that I thought.

1. OTel is W3C-Compliant, which doesn't you change they span tracing keys too easily.
2. OTel required gRPC sent via TCP+HTTP. This hopefully should also close #12 

Damn, I'm a Pythonista, but here I am doing Java. 

My work can be traced [here](https://github.com/smok-serwis/cassandra-jaeger-tracing/tree/opentracing).

**Comment by piotrmaslanka** [comment]
Since the current solution can send over traces using TCP, I don't think that this is relevant any longer.
