### ISSUE TITLE
Last request of mine - modify README.md

### ISSUE THREAD

**Issue by piotrmaslanka** [infracloudio/cassandra-jaeger-tracing#17]
Dear @bhavin192 ,

Since I've honored your request to add your commits back to my repo and keep you as a contributor in pom.xml, I need a last favour from you.

Add to README.md that this repo is no longer maintained and for people to switch over to https://github.com/smok-serwis/cassandra-jaeger-tracing

**Comment by bhavin192** [comment]
Thank you for the nudge. I have modified the README to mention the link now.
