### ISSUE TITLE
Won't work with Cassandra 4.0

### ISSUE THREAD

**Issue by piotrmaslanka** [infracloudio/cassandra-jaeger-tracing#8]
Cassandra 4.0 sports an overhauled tracing mechanism. Progress in under way to reach some sort of a compromise.

**Comment by piotrmaslanka** [comment]
As soon as I have [this post](https://henrietta.com.pl/index.php/2022/10/19/how-do-you-integrate-custom-tracing-with-cassandra/) figured out.

**Comment by bhavin192** [comment]
Yes, I was going through the Cassandra release a couple of months back, a lot of things have changed it seems. Do post here once you figure out how it is supposed to work in 4.0 :smile:

**Comment by piotrmaslanka** [comment]
Fixed partially with #9 .

**Comment by piotrmaslanka** [comment]
I hope this [sheds a light](https://henrietta.com.pl/index.php/2022/10/19/how-do-you-integrate-custom-tracing-with-cassandra/) on the implementation details.

**Comment by piotrmaslanka** [comment]
https://github.com/apache/cassandra/commit/f01d2b4a3ca114ac58d95befcab3dbbad9d960aa to be added as soon as I upgrade my cluster to Cassandra 4.1

**Comment by piotrmaslanka** [comment]
I resolved it on my branch [smok-serwis/cassandra-jaeger-tracing](https://github.com/smok-serwis/cassandra-jaeger-tracing)
